# -*- coding: utf-8 -*-
"""СИИ8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVKQZG0nfce7WxvxEydQ59hsa2iqUcg0
"""

import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.callbacks import ModelCheckpoint
from tensorflow.keras.utils import to_categorical # Опять 25

filename = "wonderland.txt"
raw_text = open(filename, encoding='utf-8').read()
raw_text = raw_text.lower()

chars = sorted(list(set(raw_text)))
char_to_int = dict((c, i) for i, c in enumerate(chars))

n_chars = len(raw_text)
n_vocab = len(chars)
print("Total Characters: ", n_chars)
print("Total Vocab: ", n_vocab)

"""Мы видим, что книга содержит менее 150000 символов и что при преобразовании в
строчные буквы в словаре есть только 47 различных символов для изучения сетью.
Гораздо больше, чем 26 в алфавите.

Это не совпало с моими данными. Любопытно...
"""

seq_length = 100
dataX = []
dataY = []
for i in range(0, n_chars - seq_length, 1):
        seq_in = raw_text[i:i + seq_length]
        seq_out = raw_text[i + seq_length]
        dataX.append([char_to_int[char] for char in seq_in])
        dataY.append(char_to_int[seq_out])
n_patterns = len(dataX)
print("Total Patterns: ", n_patterns)

X = numpy.reshape(dataX, (n_patterns, seq_length, 1))
X = X / float(n_vocab)
y = to_categorical(dataY)

model = Sequential()
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy',
optimizer='adam')

# define the checkpoint
filepath="weights-improvement-{epoch:02d}-{loss:.4f}.keras"  # .keras instead of .hdf5
checkpoint = ModelCheckpoint(filepath, monitor='loss',
verbose=1, save_best_only=True, mode='min')

from keras.callbacks import Callback
import random
import sys

int_to_char = dict((i, c) for i, c in enumerate(chars))

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from keras.callbacks import ModelCheckpoint

class TextGeneratorCallback(Callback):
    def __init__(self, dataX, int_to_char, n_vocab, generate_every=5, gen_length=300):
        super().__init__()
        self.dataX = dataX
        self.int_to_char = int_to_char
        self.n_vocab = n_vocab
        self.generate_every = generate_every
        self.gen_length = gen_length

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.generate_every != 0:
            return
        print("\n=== Text generation on epoch %d ===" % (epoch + 1))
        start = random.randint(0, len(self.dataX) - 1)
        pattern = self.dataX[start].copy()
        generated = ""
        for i in range(self.gen_length):
            x = np.reshape(pattern, (1, len(pattern), 1))
            x = x / float(self.n_vocab)
            prediction = self.model.predict(x, verbose=0)
            index = np.argmax(prediction)
            result = self.int_to_char[index]
            generated += result
            pattern.append(index)
            pattern = pattern[1:]
        print(generated)
        print()

# ХАХААХАХААХААХ 3 часа тренировки! УРА!

# Сделал тренировку на ПК

text_callback = TextGeneratorCallback(dataX, int_to_char, n_vocab, generate_every=2)

callbacks_list = [checkpoint, text_callback]


from tensorflow.keras.callbacks import TensorBoard
import datetime

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

callbacks_list.append(tensorboard_callback)

model.fit(X, y, epochs=20, batch_size=128,
callbacks=callbacks_list)

"""Тренирую на своём ПК"""

# load the network weights
filename = "weights-improvement-20-1.9948.keras"
model.load_weights(filename)
model.compile(loss='categorical_crossentropy',
optimizer='adam')

int_to_char = dict((i, c) for i, c in enumerate(chars))

import sys

# pick a random seed
start = numpy.random.randint(0, len(dataX)-1)
pattern = dataX[start]
print("Seed:")
print("\"", ''.join([int_to_char[value] for value in
pattern]), "\"" )
# generate characters
for i in range(1000):
        x = numpy.reshape(pattern, (1, len(pattern), 1))
        x = x / float(n_vocab)
        prediction = model.predict(x, verbose=0)
        index = numpy.argmax(prediction)
        result = int_to_char[index]
        seq_in = [int_to_char[value] for value in pattern]
        sys.stdout.write(result)
        pattern.append(index)
        pattern = pattern[1:len(pattern)]
print("\nDone.")